# -------------------------
# Stage 1: Build Stage
# -------------------------
FROM node:18-alpine AS builder


WORKDIR /app

COPY frontend .

RUN npm ci

RUN npm run build


# -------------------------
# Stage 2: Production Stage
# -------------------------
FROM nginx:alpine


RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
RUN apk add --no-cache curl

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
