#
# Build stage
#
FROM maven:3.8.5-openjdk-17 AS builder
WORKDIR /app
COPY pom.xml .
COPY src /app/src
RUN mvn clean package -DskipTests=true

#
# Package stage
#
FROM openjdk:17.0.2-jdk-slim

COPY --from=builder /app/target/*.jar app.jar
RUN apk add --no-cache curl

ENTRYPOINT ["java", "-jar", "app.jar"]
